#cmake /home/akbudak/parsec  -DBUILD_SHARED_LIBS=OFF -DPARSEC_WITH_HEADER_FILES=ON -DCMAKE_C_FLAGS="-fPIC -DADD_" -DPARSEC_GPU_WITH_CUDA=OFF -DCMAKE_INSTALL_PREFIX=/home/akbudak/lib/parsec -DPARSEC_WITH_DEVEL_HEADERS=ON -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -DCMAKE_Fortran_COMPILER=ifort -DPARSEC_PROF_GRAPHER=ON -DPARSEC_DIST_EAGER_LIMIT=0 -DPARSEC_DIST_SHORT_LIMIT=0 
#make -j install
#export PATH=/home/akbudak/lib/parsec/bin:$PATH
#export PKG_CONFIG_PATH=/home/akbudak/lib/parsec/lib/pkgconfig:$PKG_CONFIG_PATH

cmake /home/akbudak/parsec  -DBUILD_SHARED_LIBS=OFF -DPARSEC_WITH_HEADER_FILES=ON -DCMAKE_C_FLAGS="-fPIC -DADD_" -DPARSEC_GPU_WITH_CUDA=OFF -DCMAKE_INSTALL_PREFIX=/home/akbudak/lib/parsecnoplasma -DPARSEC_WITH_DEVEL_HEADERS=ON -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -DCMAKE_Fortran_COMPILER=ifort -DPARSEC_PROF_GRAPHER=ON -DPARSEC_DIST_EAGER_LIMIT=0 -DPARSEC_DIST_SHORT_LIMIT=0 -DBUILD_DPLASMA=OFF -DBUILD_TESTING=OFF
make -j install
export PATH=/home/akbudak/lib/parsecnoplasma/bin:$PATH
export PKG_CONFIG_PATH=/home/akbudak/lib/parsecnoplasma/lib/pkgconfig:$PKG_CONFIG_PATH
